### ISSUE TITLE
Issue a warning or fail if a specific file given as an entry point does not exist

### ISSUE THREAD

**Issue by ptmkenny** [webpro/knip#618] opened 2024-05-01 12:26 UTC
Simple `knip.json`:

```
{
  "entry": [
    "src/main.tsx!",
    "does-not-exist.ts",
  ]
}
```

`does-not-exist.ts` is a non-existent file.  When you run `npm run knip`, there is no warning or error even though `does-not-exist.ts` does not exist.

It would be great if Knip had a check that issued an error or warning if any file specified as an entry point did not exist (and maybe also for regex if the regex had no match).

For large projects that change over time, I would prefer to get an error that could be caught in CI so that I could update the `knip.config` when I make major changes that affect the entry points.

**Comment by webpro** [comment] 2024-05-02 09:03
Duplicate of #331. Agreed it's useful, but I currently just don't have the bandwidth to work on such nice-to-haves. It also requires work on the console streamer. Might pick it up later down the road.

**Closed by webpro** 2024-05-02 09:03 UTC
Labels: feature request
