### ISSUE TITLE
Commitizen with Husky

### ISSUE THREAD

**Issue by ozum** [webpro/knip#155] opened 2023-07-12 10:12 UTC
Hi,

## Situation
I use Commitizen with Husky. As a result, I don't have a `cz` command in the `scripts` of `package.json`. Instead, I have a `.husky/prepare-commit-msg` file with the following contents:

```bash
#!/bin/sh
. "$(dirname $0)/_/husky.sh"

exec < /dev/tty && npx --no-install git-cz --hook || true
```

This is the suggested config for Commitizen and Husky.

## Problem

Knip [Commitizen Plugin](https://github.com/webpro/knip/blob/main/src/plugins/commitizen) reports:

```
Unused devDependencies (1)
--------------------------
commitizen  package.json
```

However, Commitizen is used.

## Workaround

Adding following to the `package.json`.

```json
"scripts": {
  "commit": "cz"
}
```

## Kindly Request

Is it possible to add `Husky` support to `Commitizen Plugin`? It is a popular combination.

Kind Regards,

**Comment by webpro** [comment] 2023-07-12 17:44
I see on https://www.npmjs.com/package/git-cz that `commitizen` is expected be installed globally? That's a bit odd. If it would be a regular or peer dependency Knip wouldn't report it. And now you install it as a `devDependency` and it gets reported.

You can also add it to `ignoreDependencies: []`.

Just saying, the report is not coming from any plugin, `commitizen` is simply not referenced anywhere.

**Comment by ozum** [comment] 2023-07-13 04:27
As you said, I have `commitizen` as a `devDependency` as suggested [here](https://github.com/commitizen/cz-cli#optional-install-and-run-commitizen-locally), because I use it in CI (GitHub workflow). Having it in `devDependency` triggers [knip Commitizen Plugin](https://github.com/webpro/knip/blob/main/src/plugins/commitizen?rgh-link-date=2023-07-12T10%3A12%3A56Z).

However, [knip Commitizen Plugin](https://github.com/webpro/knip/blob/main/src/plugins/commitizen?rgh-link-date=2023-07-12T10%3A12%3A56Z) cannot see/know that I have `npx --no-install git-cz` in the `.husky/prepare-commit-msg` file.

The plugin should examine files in `.husky` folder and should know that I have used `git-cz`.

I would like to add a PR here, but this needs broad knowledge about how knip works.

**Comment by webpro** [comment] 2023-07-13 05:01
The `.husky/prepare-commit-ms` indicate the usage of `husky`. The [husky plugin](https://github.com/webpro/knip/tree/main/src/plugins/husky) will then read the scripts in the `.husky` folder and find `git-cz` indeed.

Unfortunately `prepare-commit-msg` was not in that list of patterns yet, but it is now in [v2.15.5](https://github.com/webpro/knip/releases/tag/2.15.5).

This will probably discover `git-cz`, but not `commitizen`. So I'm afraid this still doesn't solve your issue. Knip has no way to see that it is referenced somewhere. If `commitizen` would be a peer dependency of `git-cz`, Knip would be OK with it too.

**Comment by ozum** [comment] 2023-07-13 10:17
No problem. I'm using the workaround currently. It would be nice if it could be solved in the future.

**Comment by webpro** [comment] 2023-07-17 17:27
The issue is that Knip can't really solve it without reporting false positives for correct situations. There needs to be a (proper) reference somehow. Going to close this now, but not without telling you I really appreciate the discussions :)

**Closed by webpro** 2023-07-17 17:27 UTC
Labels: bug
