### ISSUE TITLE
Files imported through the path alias are reported as unlisted dependency

### ISSUE THREAD

**Issue by rdrezner** [webpro/knip#255] opened 2023-09-21 10:22 UTC
Hello again,

thanks for instant answer and resolution of my previous bug report.

In my project, I use webpack `file-loader` plugin to import images. I also set up an alias in the `tsconfig.json` file: `"common/*": ["src/common/*"]`.

When I import an SVG file (or any other file) through the alias `import SomeSVG from "common/image/some-svg.svg"`, `knip` reports `common/image/some-svg.svg` as unlisted dependency.

When I import the same file through the relative path `import SomeSVG from "../common/image/some-svg.svg"`, `knip` resolves redundancies correctly.

Thanks for your help.

**Comment by homburg** [comment] 2023-09-22 09:50
I was getting this error in my monorepo as well and have tried to make an example: https://github.com/homburg/hello-knip/pull/9

Seems I get the `unlisted dependency` issue specifially when running knip for a specific workspace: `knip --workspace apps/next-site`

Does this match your case @rdrezner ?

**Comment by webpro** [comment] 2023-09-23 07:04
The root cause is outlined in #206. This surfaces in Knip for imports that are not directly supported by TypeScript, causing module resolution to fail.

Aliases like that are something I would not recommend in general due to ambiguity. Still, Knip should support it just like TypeScript does.

For now you could work around it by using some kind of prefix like `~` or `#`. Even `@` is not great for the same reason of ambiguity (w/ `@scoped` packages).

**Comment by webpro** [comment] 2023-09-23 07:05
Actually, that workaround might not even work. Probably only relative import specifiers work (like you mentioned.

**Comment by webpro** [comment] 2023-09-23 07:26
Going to close this as a duplicate of #185.

**Closed by webpro** 2023-09-23 07:26 UTC
Labels: bug
