### ISSUE TITLE
How to ignore unlisted dependencies?

### ISSUE THREAD

**Issue by gajus** [webpro/knip#159] opened 2023-07-12 14:28 UTC
```
Unlisted dependencies (3)
@typescript-eslint/parser          .eslintrc.js
eslint-config-canonical            .eslintrc.js
eslint-import-resolver-typescript  .eslintrc.js
```

It looks like it infers that the plugin is in use based on which rules are mentioned:

```ts
const ruleOverrides = {
  '@typescript-eslint/dot-notation': 0,
  '@typescript-eslint/naming-convention': 0,
  '@typescript-eslint/no-misused-promises': 0,
  '@typescript-eslint/no-redeclare': 0,
  '@typescript-eslint/no-unnecessary-condition': 0,
  '@typescript-eslint/prefer-nullish-coalescing': 0,
  '@typescript-eslint/prefer-optional-chain': 0,
  '@typescript-eslint/prefer-string-starts-ends-with': 0,
  '@typescript-eslint/promise-function-async': 0,
  'canonical/filename-match-regex': 0,
  'canonical/id-match': 0,
  'canonical/prefer-import-alias': [
```

This is smart. However, in cases like [eslint-config-canonical](https://github.com/gajus/eslint-config-canonical), the config itself has a dependency on the plugins, and this becomes and undesirable.

**Comment by webpro** [comment] 2023-07-12 15:14
Knip doesn't use `rules` to infer dependencies (it looks at `extends` `plugins`, `parser` and `settings`, and also in `overrides` for the same).

But looking at https://github.com/gajus/eslint-config-canonical/blob/main/configurations/eslintrc.js, this looks like a bug in Knip. Will look into it soon!

**Comment by webpro** [comment] 2023-07-12 17:34
Not sure if I'm trying the right thing, but in that repo, either one of these configs (`knip.json`) seem to work well:

```json
{
  "entry": ["compare/*.js"],
  "eslint": ["*.js"]
}
```

```json
{
  "workspaces": {
    ".": {
      "eslint": ["*.js"]
    },
    "compare": {}
  }
}
```

**Comment by webpro** [comment] 2023-07-12 17:53
Then I wonder why it is reported as unlisted. Got a rep(r)o? :)

**Comment by webpro** [comment] 2023-07-12 18:59
Given only that config, Knip finds these dependencies (`rules` are ignored):

```
    '@contra/eslint-config',
    'eslint-plugin-relay',
    '@typescript-eslint/parser',
    'eslint-import-resolver-typescript',
    'eslint-config-canonical',
```

**Comment by webpro** [comment] 2023-07-12 19:03
Normally the dependencies would be direct or peer dependencies. Not sure how Knip could make an exception here without affecting other setups.

**Comment by webpro** [comment] 2023-07-17 17:31
Going to close this issue. Since the dependencies are "directly" referenced in the ESLint config, Knip can only assume they should be listed in `package.json`.

Fixing this issue would mean transitive dependencies are OK, and I prefer not to go that way.

**Closed by webpro** 2023-07-17 17:31 UTC
Labels: discussion

**Comment by gajus** [comment] 2023-07-17 19:24
That's fair.

I would still consider `ignoreUnlisted` configuration for cases where it is desirable to support transitive dependencies.

I am trying to restructure out project to avoid this altogether.

**Comment by DavidArutiunian** [comment] 2023-10-09 18:49
@webpro I have a same issue. 

I'm sharing config files across multiple repos as an npm library, which itself contains eslint configuration and dependencies.

Typically eslint config of an app consuming this library looks like this:

```javascript
const merge = require("deepmerge");
const { createEslintConfig } = require("@omnic/widget-config");

const rootConfig = createEslintConfig();

module.exports = merge(rootConfig, {
  root: true,
  env: { node: true },
  rules: { "@typescript-eslint/no-var-requires": "off" },
});
```

And here is my output

![](https://github.com/webpro/knip/assets/17799810/4c117ec1-e8da-41b6-8b4d-6854c3630ddc)

> Fixing this issue would mean transitive dependencies are OK to directly depend on, and I prefer not to go that way.

Isn't it possible to optionally enable transitive dependencies check? It would be very helpful in case of using Knip for module federations for example, cause they usually have some shared configs/ui-kits, and duplicating all the dependencies is not a way

**Comment by webpro** [comment] 2023-10-09 19:05
> Isn't it possible to optionally enable transitive dependencies check? 

This is a common yet non-trivial issue to solve. It's on my radar.

> P.S. Also can't figure out how to deal with these .svg imports (I'm using vite + svgr plugin)

This is usually worked around by using relative imports (e.g. `./src/icon.svg`).

**Comment by mwmcode** [comment] 2024-12-18 16:58
Hi @webpro I have two (related?) issues in my RN codebase:
```sh
Unused dependencies (1)
react-native-background-fetch  package.json
Unlisted dependencies (1)
domhandler  .../RenderHTML/index.tsx
```
- `react-native-background-fetch` is required by [react-native-background-geolocation](https://github.com/transistorsoft/react-native-background-geolocation/blob/master/help/INSTALL-IOS-AUTO.md)
- `domhandler` seems to be exposed by [htmlparser2](https://www.npmjs.com/package/htmlparser2?activeTab=dependencies)

is there a way to 

```js
// knip.json
{
  "ignoreUnUsedDependencies": ["pattern/**/*"],
  "ignoreUnListedDependencies": ["pattern/**/*"]
}
```

>I can probably add `domhandler` as a dependency, but I don't know how to go about `react-native-background-fetch` reported as unused. Any ideas?

**Comment by webpro** [comment] 2024-12-18 18:13
This issue's already closed. Please create a reproduction and file a new one if you want us to look into it.

**Comment by mwmcode** [comment] 2024-12-18 18:16
My bad. Found a workaround here https://knip.dev/reference/configuration#ignoredependencies
