### ISSUE TITLE
Read `testMatch` field in jest configs to find jest tests

### ISSUE THREAD

**Issue by davidturissini** [webpro/knip#217] opened 2023-08-23 18:09 UTC
We have a custom `testMatch` in our jest config file. It matches `<rootDir>/**/*.jest.{ts,tsx}`. Running `npx knip` in the root directory with the following configuration reports that all `*.jest.ts` and `*.jest.tsx` files are unused and can be removed: 

```ts
import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  jest: {
    config: PATH_TO_OUR_CONFIG
  },
};

export default config;

```

I also tried the following with no success:

```
const config: KnipConfig = {
  jest: {
    config: PATH_TO_OUR_CONFIG,
    entry: ['**.jest.ts']
  },
};
```

I took a look at the [plugin source code](https://github.com/webpro/knip/blob/main/src/plugins/jest/index.ts) and there is no indication that `testMatch` is observed at all.

Happy to provide a reduced repro if you need.

Edited to add:
knip seems to be loading my jest configuration correctly. It is in a non-standard location and is not being reported as unused.

**Comment by webpro** [comment] 2023-08-24 08:26
The main goal of the plugins is to find dependencies. Everything else is basically patches to make that happen.

In your case you need to add `entry` items as you did. However, the glob does not go into sub dirs. What will probably work, but might me inefficient is this, basically just like in the `testMatch`:

```ts
const config: KnipConfig = {
  jest: {
    config: PATH_TO_OUR_CONFIG,
    entry: ['**/*.jest.{ts,tsx}']
  }
};
```

**Comment by davidturissini** [comment] 2023-08-24 16:12
> The main goal of the plugins is to find dependencies. Everything else is basically patches to make that happen.
> 
> In your case you need to add `entry` items as you did. However, the glob does not go into sub dirs. What will probably work, but might me inefficient is this, basically just like in the `testMatch`:
> 
> ```ts
> const config: KnipConfig = {
>   jest: {
>     config: PATH_TO_OUR_CONFIG,
>     entry: ['**/*.jest.{ts,tsx}']
>   }
> };
> ```

Thanks @webpro
I also tried doing a deep glob pattern like you suggested but all of my jest files are still being considered unused. I suspect there is something going on in the plugin that is ignoring this.

**Comment by webpro** [comment] 2023-08-24 16:17
You could do a debug run and see whether the plugin is enabled, how workspaces in a monorepo are configured, etc.

**Comment by webpro** [comment] 2023-08-28 13:49
Can I close this one? Or else, you have a rep(r)o?

**Comment by davidturissini** [comment] 2023-08-28 22:17
@webpro I think I've figured this out. Want to confirm what I'm seeing. I'm not 100% sure this is a bug.

I am using a monorepo, one of our apps is located at path `app`. This configuration reports all jest files as unused:
```
const config: KnipConfig = {
  jest: {
    config: PATH_TO_OUR_CONFIG,
    entry: ['**.jest.ts']
  },
};
```

This configuration does NOT report jest files as unused:

```
const config: KnipConfig = {
  jest: {
    config: PATH_TO_OUR_CONFIG,
    entry: ['**.jest.{ts,tsx}']
  },
  workspaces: {
     "app": {
       jest: {
         entry: ['**/*.jest.{ts,tsx}'],
       }
     }
   }
 };
```

`jest` is a dependency in the root package.json, not in any sub packages. I would've expected `jest` to apply to all workspaces but it appears it does not. Is this expected?

**Comment by webpro** [comment] 2023-08-29 07:16
> `jest` is a dependency in the root package.json, not in any sub packages. I would've expected `jest` to apply to all workspaces but it appears it does not. Is this expected?

This should work as you expected, but could be a duplicate of #213.

The top-level `jest` config should be moved to a `"."` named workspace like so:

```ts
const config: KnipConfig = {
  workspaces: {
     ".": {
      jest: {
        config: PATH_TO_OUR_CONFIG,
        entry: ['**.jest.{ts,tsx}']
       }
     },
     "app": {
       jest: {
         entry: ['**/*.jest.{ts,tsx}'],
       }
     }
   }
 };
```

Does that help?

**Comment by davidturissini** [comment] 2023-08-29 16:12
No- still same issue. `.jest.{ts,tsx}` files still not considered as entry points in child packages. I'd be willing to bet that it is the same issue as #213. I'm ok to close this- we have a workaround

**Comment by webpro** [comment] 2023-08-30 04:32
Yeah without repro there isn't much I can do. Glad you have a workaround :)

**Closed by webpro** 2023-08-30 04:32 UTC
Labels: bug
