### ISSUE TITLE
Consider `projects` in Jest config

### ISSUE THREAD

**Issue by alecmev** [webpro/knip#189] opened 2023-08-03 16:37 UTC
My Jest config looks something like this:

```ts
import { readdirSync } from 'node:fs';

const project = (name) => ({
  setupFilesAfterEnv: ['<rootDir>/../../jest.setup.ts'],
  // ...
});

const CONFIG = {
  projects: readdirSync('packages').map((x) => project(x)),
  // ...
};

export default CONFIG;
```

Knip doesn't look at `projects`, so `jest.setup.ts` and the stuff it imports end up being marked as unused.

**Comment by alecmev** [comment] 2023-08-03 17:07
Are you sure you aren't thinking of presets? Grepping [the plugin](https://github.com/webpro/knip/blob/d080ed2d59e2f497cbe3ba5bbb10e00d15f98292/src/plugins/jest/index.ts) doesn't reveal any occurrences of `projects`.

**Comment by webpro** [comment] 2023-08-03 17:10
Apologies, you're right. Probably an easy fix then :)

**Comment by webpro** [comment] 2023-08-04 20:29
:rocket: _This issue has been resolved in v2.18.0. See [Release 2.18.0](https://github.com/webpro/knip/releases/tag/2.18.0) for release notes._

**Closed by webpro** 2023-08-04 20:29 UTC
Labels: feature request

**Comment by webpro** [comment] 2023-08-04 20:31
Also caught another uncovered `runner` prop :)

**Comment by alecmev** [comment] 2023-08-05 14:09
Thank you!

**Comment by alecmev** [comment] 2023-08-05 14:27
There's a mistake here, Jest is weird about the resolution of the paths in projects, it's done relative to the root of the project, not the root of the repository, so given `setupFilesAfterEnv: ['<rootDir>/../../jest.setup.ts']` Knip ends up looking for it in `repo_root/../..`, not in `repo_root/packages/foo/../..`. I wish I could just put `setupFilesAfterEnv` in the base config of Jest, but that doesn't work at all.

**Comment by webpro** [comment] 2023-08-06 13:34
Are you sure? Knip replaces `<rootDir>` with the dir of the project.

I just added f32d8156d00b14958416911989722c6ee01a8ca7 for extra test coverage.

In the plugin the variable is called `cwd` which might lead to confusion?

**Comment by alecmev** [comment] 2023-08-06 13:38
It definitely breaks if there are `..` involved (with the configuration from the original post). Note that `setupFilesAfterEnv` is in `projects`, not in the root config, as it is in the fixture linked :stuck_out_tongue:

**Comment by webpro** [comment] 2023-08-06 13:43
It's `path.join(rootDir, optionValue)` so I think the issue is not the `..`, but the fact that the linked file is in a different workspace.

What is the result you're seeing?

**Comment by alecmev** [comment] 2023-08-06 14:30
I get the following:

```
Unused files (1)
jest.setup.ts
Unresolved imports (1)
/dir-two-levels-below-repo-root/jest.setup.ts  jest.config.js
```

**Comment by webpro** [comment] 2023-08-08 06:53
The idea is that modules are isolated, shouldn't traverse like that in a monorepo.

E.g. ESLint can reference other workspaces with `extend` specifiers like `@org/eslint-config-name/config-file`.

**Comment by alecmev** [comment] 2023-08-08 09:34
Hmm, my intention is to have as much development boilerplate in the root as possible. My `jest.setup.ts` has just this:

```ts
import { toMatchImageSnapshot } from 'jest-image-snapshot';
import { toBeDeepCloseTo } from 'jest-matcher-deep-close-to';

expect.extend({ toMatchImageSnapshot, toBeDeepCloseTo });
```

And currently I'm getting away with not having a copy/symlink of it in every package. Also makes sense to colocate it with `jest.config.js`, as one is basically an extension of the other.

What would you change about this? :thinking:

**Comment by webpro** [comment] 2023-08-08 09:52
Maybe you can tell Jest to look for `jest.setup.ts` in the root?

Either way, this is the reason I didn't went too far with trying to support all types of cross-package references like this and try to be relatively strict about it. Whatever you end up with, I hope there's a way Knip plays nice with to (probably some combo of `ignore` and `jest` in root and/or packages using Jest).

**Comment by alecmev** [comment] 2023-08-08 10:06
Hmm, I think there's a misunderstanding. Confusingly, in the examples above, Jest resolves `<rootDir>` to `/root/package/foo`, not `/root`. And I can't put `setupFilesAfterEnv` in the main config; if I do that, then its effects don't propagate to the projects. Both `jest.config.js` and `jest.setup.ts` are located in the root of the monorepo, and I run Jest from the root as well. There's zero Jest configuration in any of the packages themselves. Let me know if you'd like me to setup a repro!

**Comment by webpro** [comment] 2023-08-08 12:15
This result is expected behavior: https://github.com/webpro/knip/issues/189#issuecomment-1666879431. You can use `ignore` and `jest` entry/config items in `knip.json` for Knip to handle this better. Currently I don't really feel like messing around isolated packages too much.

Feel free to open a repo if you think there's a bug on Knip. It could also be useful as a reference to discuss how to best handle the situation as it might be a common setup.

**Comment by alecmev** [comment] 2023-08-10 15:58
Created a repro: https://github.com/alecmev/knip-repro-189 You can try playing around with the config of Jest, this is the only way to have a reusable `jest.setup.js`, AFAIK.

**Comment by alecmev** [comment] 2023-08-18 17:21
@webpro Have you had a chance to take a look at the repro? Just wondering if you believe that it's an anti-pattern and I should try setting it up differently, or if it's something that Knip may support in the future.

**Comment by webpro** [comment] 2023-08-19 13:52
Yes, I looked at it and this is Knip's behavior as expected.

Don't want to leave anyone behind, but some tools allow things that are hard to deal with for Knip. Another notable example is ESLint. Luckily they ESLint has realized this too and are going the sane route with the new explicit `eslint.config.js` way of configuring things.

So unfortunately, no, I'm not eager to spend my time here, but of course I would be happy to look into PRs with sane solutions.

**Comment by alecmev** [comment] 2023-10-11 13:05
A quick update for future readers, I ended up getting rid of `rootPath` and just pre-resolving everything:

```ts
import { readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const project = (name) => ({
  setupFilesAfterEnv: [fileURLToPath(new URL('jest.setup.ts', import.meta.url))],
  // ...
});

const CONFIG = {
  projects: readdirSync('packages').map((x) => project(x)),
  // ...
};

export default CONFIG;
```
