### ISSUE TITLE
Knip does not ignore gitignored directory when it has bad permissions

### ISSUE THREAD

**Issue by ChristophP** [webpro/knip#172] opened 2023-07-25 20:44 UTC
Hi,

I'm using the latest knip 2.17.0 on a Linux machine.

This is my knip config:
```js
{
  "entry": ["src/app.js", "scripts/**/*.js"],
  "project": ["**/*.js"]
}
```

I have a directory called `mongodata` in the project root, which contains MongoDB data from a DB that's running in a docker container. Since it's running in the docker container it has different file permission than the rest of the project files.
The mongodata folder is listed in my `.gitignore`.

Nevertheless when I run knip I get this:
![grafik](https://github.com/webpro/knip/assets/5880236/68c7cc36-b62f-49b2-b192-423a87df26f5)

I even tried adding `ignore: ["mongodata/"]` to the knip.json, but I still got the error.

**Comment by ChristophP** [comment] 2023-07-25 20:48
It can probably be reproduced by running this in an existing knip project
```
mkdir somedir
chown -R 1400:1400 somedir
```

**Comment by webpro** [comment] 2023-07-26 09:02
Can't seem to reproduce it here (I'm on macOS).

Not sure if easily fixable by Knip. Perhaps easiest to update config to something like this:

```json
{
  "entry": ["src/app.js", "scripts/**/*.js"],
  "project": ["{src,scripts}/**/*.js"]
}
```

Would that work for you?

**Comment by ChristophP** [comment] 2023-07-26 16:31
Hi @webpro , 

I checked a bit more I there was one thing missing in my previous description to reproduce.

In an existing knip project do
```
mkdir somedir
chown -R 1400:adm somedir # change the ownership to user 1400 and group adm
chmod -R 400 somedir            # make the dir only accesible to the owner

npx knip # crashes due to lacking file permissions
```

This in itself is not so weird that it errors for lacking permissions. The weird thing is that the error still occurs even thought the directory is in the `.gitignore`. This means that knip must somehow try to scan the directory even if it should be ignored.

Can you reproduce it this way?

**Comment by webpro** [comment] 2023-07-27 05:13
Globbing the file system is done by [globby](https://github.com/sindresorhus/globby), which in turn uses [fast-glob](https://github.com/mrmlnc/fast-glob). It is configured to take the `.gitignore` into account.

I see fast-glob has a `suppressErrors: true` option. I will think about either using that option or try/catching the error and printing a warning, so Knip's process isn't halted.

**Comment by ChristophP** [comment] 2023-07-27 12:11
> I see fast-glob has a suppressErrors: true option. I will think about either using that option or try/catching the error and printing a warning, so Knip's process isn't halted.

That would be a workaround. However it seems to me that, if the globbing correctly ignored the items from `.gitignore` the error shouldn't happen in the first place, should it?

**Comment by ChristophP** [comment] 2023-07-27 20:43
I think I have narrowed down the last call before the error happens. It should be `getEntryPathFromManifest` function
https://github.com/webpro/knip/blob/main/src/index.ts#L155

**Comment by ChristophP** [comment] 2023-07-27 21:11
`getEntryPathFromManifest` in turn calls `_glob` here https://github.com/webpro/knip/blob/main/src/util/modules.ts#L57C2-L57C2 .
It seems like `globby` still tries to access the directory even when it's gitignored.

Now that I understand that I think you're sugesstion of catching or supressing the error is probably the way to go here.

**Comment by ChristophP** [comment] 2023-07-27 21:16
Btw, I modified my `knip.json` to have this content
```json
{
  "entry": ["src/app.js", "scripts/**/*.js"],
  "project": ["src/**/*.js", "scripts/**/*.js"]
}
```
and I still get the same error. Even though the offending `mongodata/` directory is above `src` and `scripts` AND contained in `.gitignore`. Very strange

**Comment by ChristophP** [comment] 2023-08-01 12:15
Ah that makes sense. So `globby` using doing a recursive lookup for `.gitignore` files in all subdirectories and crashes when it can't read one.
It seems this is a strange behavior on `globby`s part, or that at least would be nice if `globby` had some way of skipping directories it can't read. I added an issue on globby side for this.

In the mean time your suggestions sound good.
What I also found was this option https://github.com/sindresorhus/globby#ignorefiles

If knip somehow exposed this option then a user (like me) could specify his/her own pattern. In this case I could tell `knip`/`globby` that  my ignore file pattern is simply `.gitignore` instead of the default `**/.gitignore`.

**Comment by ChristophP** [comment] 2023-08-01 17:11
Update: Seems like the author of globby considers the current behavior a bug.

**Comment by webpro** [comment] 2023-08-05 09:22
Thanks!

There's currently no way to override the hard-coded `**/.gitignore` pattern in globby.

Still not sure about that workaround in Knip, but will keep this ticket open.

**Comment by ChristophP** [comment] 2023-08-05 09:47
Got it.

My current workaround is to just aff read permissions for all for the Folder thst causes the Bug, which let's me use knip normally. 

Knowing that the globby author considers this a bug probably means that it will get fixed at some point.
With workaround exising maybe knip doesn't have to implement its own workaround and just wait until it gets fixed upstream.

Feel free to open or close this issue as you see fit.

**Comment by webpro** [comment] 2023-09-20 21:53
Since the actual issue is upstream, I didn't hear from anyone else, and searching for `EACCESS` in the globby and fast-glob repos also don't show many issues, I'm going to close this.

**Closed by webpro** 2023-09-20 21:53 UTC
Labels: bug

**Comment by ChristophP** [comment] 2023-09-21 07:20
That's fine. The [upstream issue](https://github.com/sindresorhus/globby/issues/254#issuecomment-1666768414) is labelled with "help wanted" so it looks like they are looking for a contribution. It could take a while until it's fixed.

**Comment by phiresky** [comment] 2023-11-02 16:56
I'm hitting the same error. I have a huge /notes directory in my repo that is gitignored and contains all sorts of files. Deep inside there's something not readable by my current user, and knip fails with `Error: EACCES: permission denied, scandir` on that directory.

**Comment by ChristophP** [comment] 2024-02-11 14:32
@webpro FYI seems like globby fixed this issue upstream https://github.com/sindresorhus/globby/pull/259

**Comment by phiresky** [comment] 2024-02-11 14:34
I glanced at their fix but if I understand correctly it only solves the issue in narrow cases - when the permissionless files are in one of the locations that's in the hardcoded ignore list (not when it's in a gitignore file)

**Comment by ChristophP** [comment] 2024-02-11 16:02
Ah ok, I didn't Look at it in depth yet but thought it was the Kind of fix discussed in this issue.

> doesn't apply to knip though because we fixed it differently
Ah so knip rolled it's own solution?

**Comment by webpro** [comment] 2024-02-11 16:04
> Ah so knip rolled it's own solution?

@phiresky did! In #426 ❤️

**Comment by ChristophP** [comment] 2024-02-11 16:26
Ah fantastic. So knip doesn't even use globby in this case anymore. 👍

**Comment by webpro** [comment] 2024-02-11 16:28
That PR replaces cq removes globby from the dependency list indeed.
