### ISSUE TITLE
`@commitlint/cli` - Unused devDependencies only in CLI

### ISSUE THREAD

**Issue by RebeccaStevens** [webpro/knip#542] opened 2024-03-12 03:26 UTC
When I run `knip` locally everything passes, but it CI it fails. I've got no idea why.

Here's my CI output:
https://github.com/RebeccaStevens/template-typescript-node-package/actions/runs/8243105381/job/22543137223

**Comment by webpro** [comment] 2024-03-21 13:46
Closing this as I think it's not a bug in Knip, but rather a different environment with different (npm) scripts, files present, etc.

**Closed by webpro** 2024-03-21 13:46 UTC
Labels: bug

**Comment by RamAvni** [comment] 2025-07-25 12:57
Any update on this one?
