### ISSUE TITLE
Incorrect unlisted dependency with import for type-only dependency

### ISSUE THREAD

**Issue by ericcornelissen** [webpro/knip#28] opened 2022-11-21 20:37 UTC
I [installed `knip` on one of my projects](https://github.com/ericcornelissen/eslint-plugin-top/pull/127) and faced an issue with a dependency I have on `@types/estree`.

Specifically, [`@types/estree`](https://www.npmjs.com/package/@types/estree) only exists as a `@types/` package - there's no [`estree`](https://www.npmjs.com/package/estree) package. However, to import types from `@types/` package in TypeScript, you must (I believe) import it from the "base" package (which happens [here](https://github.com/ericcornelissen/eslint-plugin-top/blob/8fa9fb25239294d6a1d3b5d053824348eb73ca68/lib/rules/no-top-level-variables.ts#L1)). But since [`estree`](https://www.npmjs.com/package/estree) doesn't exist, `knip` cannot find the dependency and reports an unlisted dependency.

Even if this can be fixed by updating my TypeScript configuration, I would expect `knip` to support the import style I'm currently using.

**Comment by webpro** [comment] 2022-11-23 14:06
Thanks for reporting this, it is indeed not handled properly pre-v1.

You could try the latest alpha release (`npm install -D knip@alpha`) that should have this covered. Updated docs for this are at https://github.com/webpro/knip/tree/feature/workspaces-and-plugins.

Not sure yet if I'm going fix this in pre-v1, but will leave this ticket open.

**Comment by ericcornelissen** [comment] 2022-11-23 21:43
I tested the latest alpha release (i.e. `knip@1.0.0-alpha.0`) on the linked branch and it doesn't seem to resolve the issue - but it doesn't seem to work in general as `knip` is now reporting unused exports and devDependencies which it wasn't before (to be fair, I'm not spotting devDependencies in the `0.13.2` output at all).

Also, not sure if you're looking for feedback on the alpha release, but `knip` is reporting git and [shellcheck](https://github.com/koalaman/shellcheck) as unlisted dependencies in `package.json`. I'm not sure about a good resolution, but the current approach seems non-ideal from my point of view. I guess I could `--exclude` the "unlisted" issue type but I'd prefer smarter resolution for `package.json` script detection (e.g. "git" could be allowed if the project is detected to be a git repository) or a way to manually specify dependencies that are allowed in `package.json` scripts.

**Comment by webpro** [comment] 2022-11-24 09:33
> I tested the latest alpha release (i.e. `knip@1.0.0-alpha.0`) on the linked branch and it doesn't seem to resolve the issue - but it doesn't seem to work in general as `knip` is now reporting unused exports and devDependencies which it wasn't before (to be fair, I'm not spotting devDependencies in the `0.13.2` output at all).

This "dev" versus "production" mode has been turned around for v1.  That means "dev" mode is the default, and you would have to use `--production` to get what was the default pre-v1. For some reasoning behind this, when developing Knip further I realized a few things:

- When having to choose which one is the default, I think "dev mode" is easier to understand and easier to configure for people new to Knip. This probably does not hold true for some type of projects, such as small and more "pure" Node.js projects that don't have any of these more "frontend-focused" dependencies. Larger projects that require more custom dependency resolvers etc. tend to benefit more from Knip, as far as I can see now.
- In terms of files to include, production mode is like a subset of dev mode. Hoping to make this configuration easier -- I'm not 100% sure yet about the "API" for this -- currently you can mark production globs by appending the `!` suffix to them.

There is a minimal section about this at https://github.com/webpro/knip/tree/feature/workspaces-and-plugins#production-mode.

> Also, not sure if you're looking for feedback on the alpha release, but `knip` is reporting git and [shellcheck](https://github.com/koalaman/shellcheck) as unlisted dependencies in `package.json`. I'm not sure about a good resolution, but the current approach seems non-ideal from my point of view. I guess I could `--exclude` the "unlisted" issue type but I'd prefer smarter resolution for `package.json` script detection (e.g. "git" could be allowed if the project is detected to be a git repository) or a way to manually specify dependencies that are allowed in `package.json` scripts.

Thanks a lot for taking the time to report this. This is a feature I'm equally excited and terrified about. You can use the undocumented (so sorry about that) feature to allow/ignore such system/global binaries like this:

```json
{
  "ignoreBinaries": ["git", "shellcheck"]
}
```

Binaries that are excluded by default already are `npm`, `npx`, `node`, `yarn` and `pnpm`.

Your suggestion about detecting `git` is a good one, I'll think about that some more. The reason I'm also terrified about this feature in general, is that `shellcheck` (or `rm` or `ls`, etc) could be an npm dependency as well, so this will probably lead to many false positives.

So what you get by default is Knip detecting binaries in npm scripts that are not in list of (dev) dependencies. The false positives that Knip will not be able to detect can be added to `ignoreBinaries`.

Again, apologies for wasting your time. Hopefully Knip will save you some in the future. Also happy to hear any further feedback or questions you may have.

**Comment by ericcornelissen** [comment] 2022-11-25 19:06
> This "dev" versus "production" mode has been turned around for v1. That means "dev" mode is the default, and you would have to use --production to get what was the default pre-v1. 

Thanks for clarifying, I missed this while skimming the new documentation for the alpha release.


> [...] I'm not 100% sure yet about the "API" for this -- currently you can mark production globs by appending the `!` suffix to them.

This kind of confuses me (having also read [this comment](https://github.com/ericcornelissen/eslint-plugin-top/pull/127#issuecomment-1326742534)). It's not clear to me what, for example, the implications of specifying a production entrypoint are.


> Thanks a lot for taking the time to report this. This is a feature I'm equally excited and terrified about. [...]

I see, that actually makes a lot of sense. Having the option to ignore/allow certain executable suffices from my perspective. In general I don't like using system dependencies so I'm actually very happy `knip` reports them (but seeing as they're sometimes necessary, being able to allow them is a necessary feature).


> The reason I'm also terrified about this feature in general, is that shellcheck (or rm or ls, etc) could be an npm dependency as well, so this will probably lead to many false positives.
>
> So what you get by default is Knip detecting binaries in npm scripts that are not in list of (dev) dependencies. The false positives that Knip will not be able to detect can be added to ignoreBinaries.

If I'm understanding your concerns correctly, I think you can solve this by checking if a given binary appears in the `node_modules/.bin` directory.

---

No worries about "wasting my time", I'm happy to try things out and help improve the project 😄

**Comment by webpro** [comment] 2022-11-26 11:04
> > [...] I'm not 100% sure yet about the "API" for this -- currently you can mark production globs by appending the `!` suffix to them.
> 
> This kind of confuses me (having also read [this comment](https://github.com/ericcornelissen/eslint-plugin-top/pull/127#issuecomment-1326742534)). It's not clear to me what, for example, the implications of specifying a production entrypoint are.

The idea is that (only) globs with this suffix are used when `--production` mode is enabled. Production mode means:

- Non-production files (tests, configuration files, etc) are not included in the analysis (e.g. a test might be the only thing referencing production code, when maybe both can be removed).
- Exported types are not part of the analysis.
- With the extra `--strict` flag, production code is supposed to use only `dependencies` (and not `devDependencies`); and in a monorepo this will also assume self-containing workspaces (i.e. don't rely on (hoisted) dependencies of other/ancestor workspaces).

> If I'm understanding your concerns correctly, I think you can solve this by checking if a given binary appears in the `node_modules/.bin` directory.

The issue is more that if a binary is referenced in an npm script, but not listed in `package.json` (and thus probably also not available in `node_modules/.bin`), there's no way for Knip to know whether that was supposed to be an npm package or an OS binary. Then it will be marked as "unlisted" (unless added to `ignoreBinaries`).

**Comment by ericcornelissen** [comment] 2022-11-26 12:14
> The idea is that (only) globs with this suffix are used when `--production` mode is enabled. [...]

Okay, thanks for elaborating.

> there's no way for Knip to know whether that was supposed to be an npm package or an OS binary.

I see, I was misunderstanding your concern, but that clarifies it.

**Comment by webpro** [comment] 2022-12-22 16:14
Closing this as I believe the original issue has been fixed

**Closed by webpro** 2022-12-22 16:14 UTC
Labels: bug
