### ISSUE TITLE
vitest broken at version 2.32.0

### ISSUE THREAD

**Issue by jthr-sbab** [webpro/knip#292] opened 2023-10-11 14:41 UTC
Hi, 

I run a vite-project with vitest for testing. 
I've done no config for either project in the knip.ts and it all works fine at version 2.31.0. 
But when I updated to version 2.32.0 (or newer) it list my test-files as unused. 
I see that u done some kind of refactoring for vitest in that version and maybe you broke something. 

Br

**Comment by webpro** [comment] 2023-10-11 20:47
Can you share more details? What does the Knip config look like? And the Vitest config? Is this in a public repo I can take a look at?

**Comment by birtles** [comment] 2023-10-12 02:39
I'm likewise struggling to upgrade to 2.32.0. Everything works with 2.31.0 but as of 2.32.0 I get 112 issues. I'm not sure if it's related to this because I'm still having a very hard time trying to narrow down what changed. I've compared the debug output from both versions but haven't gotten any clues yet.

My [knip config](https://github.com/birchill/10ten-ja-reader/blob/main/knip.ts) and [failure log](https://github.com/birchill/10ten-ja-reader/actions/runs/6490274149/job/17625805159?pr=1357) if it's of any interest.

**Comment by jthr-sbab** [comment] 2023-10-12 07:04
Knip.ts:

`import type { KnipConfig } from "knip";

const config: KnipConfig = {
  workspaces: {
    ".": {
      husky: {
        config: [".husky/pre-commit"],
      },
    },
    frontend: {
      entry: ["src/index.tsx", "src/testUtils.tsx"],
      ignore: [
        "src/generated/graphql.ts",
        "src/react-app-env.d.ts",
        "src/GraphQLFetcher.ts",
        "**/pact",
        "**/public/*.js",
      ],
    },
    backend: {
      entry: ["src/index.js"],
      project: ["src/**/*.js"],
    },
  },
};

export default config;
`

citest.config.ts:
`
import { defineConfig, mergeConfig } from 'vitest/config';
import viteConfig from './vite.config';

export default defineConfig((configEnv) =>
    mergeConfig(
        viteConfig(configEnv),
        defineConfig({
            test: {
                environment: 'jsdom',
                globals: true,
                include: ['**/*.test.{ts,tsx}'],
                setupFiles: ['./src/setupTests.tsx'],
                mockReset: true, 
                coverage: {
                    provider: 'v8',
                    all: true,
                    include: ['src'],
                    exclude: [
                        '**/*.test.*',
                        '**/*.d.ts',
                        '**/types',
                        '**/*.pact.ts',
                        '**/queries/*',
                        '**/testUtils.tsx',
                        '**/setupTests.tsx',
                        '**/pactUtils.ts'
                    ],
                    reporter: ['text', 'json', 'lcov', 'html']
                }
            }
        })
    )
);
`
vite.config.ts:
`
/// <reference types="vitest" />
import react from '@vitejs/plugin-react-swc';
import path from 'path';
import { defineConfig } from 'vite';
import svgr from 'vite-plugin-svgr';
import checker from 'vite-plugin-checker';

export default defineConfig(() => {
    return {
        root: './',
        server: {
            proxy: {
                '/api': {
                    target: 'http://localhost:5000',
                    changeOrigin: true,
                    cookieDomainRewrite: ''
                }
            }
        },
        plugins: [
            react({ plugins: [['@swc/plugin-styled-components', {}]] }),
            svgr(), 
            checker({
                typescript: true
            })
        ]
    };
});
`

**Comment by webpro** [comment] 2023-10-12 07:07
I've pushed a few fixes in [v2.33.2](https://github.com/webpro/knip/releases/tag/2.33.2), can you please try that and see whether the issues are fixed?

Otherwise, please use code blocks (surround with three backticks).

**Comment by jthr-sbab** [comment] 2023-10-12 07:21
Did not solve my problem. :S

**Comment by webpro** [comment] 2023-10-12 09:54
:rocket: _This issue has been resolved in v2.33.3. See [Release 2.33.3](https://github.com/webpro/knip/releases/tag/2.33.3) for release notes._

**Closed by webpro** 2023-10-12 09:54 UTC
Labels: bug

**Comment by webpro** [comment] 2023-10-12 09:55
This might fix it, but not 100% sure since I haven't seen a good reproduction.

**Comment by jthr-sbab** [comment] 2023-10-12 10:03
Solved it! Thanks so much, I really worship the work you do!

**Comment by webpro** [comment] 2023-10-12 10:14
In that case, to be fair, the Vitest plugin wasn't really working at all in your case, it didn't return any dependencies. I didn't know it could be a function. So that's fixed now. But since the test file patterns were a global Knip thing before, it may have _seemed_ to work fine.
