### ISSUE TITLE
Object destructuring assignment not recognized as reference

### ISSUE THREAD

**Issue by justingrant** [webpro/knip#493] opened 2024-02-04 21:56 UTC
Repro: 

```ts
import * as S from "./styled";

const { Divider, TabBar } = S;
// OR 
const Divider = S.Divider;
const TabBar = S.TabBar;

export { Divider, TabBar };
```

Expected: either assignment syntax is recognized by knip as a reference of an import
Actual: only the ES5 assignment syntax is recognized. The destructuring assignment is not.

**Comment by webpro** [comment] 2024-02-05 06:48
That's not a repro. Sounds like a duplicate of #475 (would be great of you could test that potential fix).

**Closed by webpro** 2024-02-05 06:48 UTC
Labels: bug

**Comment by justingrant** [comment] 2024-02-05 07:30
`npx knip@nsexport` does not exhibit the problem reported in this issue. 🎉 

The case here is a bit different from #475:
* This issue: imports from `import *` are referenced by name, but with destructuring assignment without a `...rest`.
* Imports from `import *` are referenced not by name, e.g. via `...`, `Object.entries`, or some other code that references every import in that namespace. This is #475.

Not sure it matters because your new version fixes both cases, which is great. 

Thanks again!
