### ISSUE TITLE
Dependency resolve failure for yarn berry (pnp)

### ISSUE THREAD

**Issue by flex-mookeun** [webpro/knip#369] opened 2023-11-28 05:56 UTC
Hi, 

I'm trying out knip on my yarn pnp project, I got following error when running knip.
This is reproducible in the simpliest pnp project (please see attchment).

[knip-test.zip](https://github.com/webpro/knip/files/13484039/knip-test.zip)

Thanks in advance!

```
/Users/mookeun/Projects/knip-test/.pnp.cjs:10938
      Error.captureStackTrace(firstError);
            ^

Error: @pnpm/npm-resolver tried to access @pnpm/logger (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: @pnpm/logger
Required by: @pnpm/npm-resolver@virtual:47d882f261ff1e5ee9185b15c631d6da6eccdce872e60532db0cc73cc7c1aa45bb3db61258f118fffb172d14412b3284e347ac28695fbdd934c1b1979739155e#npm:18.0.0 (via /Users/mookeun/Projects/knip-test/.yarn/__virtual__/@pnpm-npm-resolver-virtual-1b644e1381/0/cache/@pnpm-npm-resolver-npm-18.0.0-c814e1b91c-a35fbc34f9.zip/node_modules/@pnpm/npm-resolver/lib/)

Ancestor breaking the chain: @pnpm/workspace.pkgs-graph@npm:2.0.11


Require stack:
- /Users/mookeun/Projects/knip-test/.yarn/__virtual__/@pnpm-npm-resolver-virtual-1b644e1381/0/cache/@pnpm-npm-resolver-npm-18.0.0-c814e1b91c-a35fbc34f9.zip/node_modules/@pnpm/npm-resolver/lib/pickPackage.js
- /Users/mookeun/Projects/knip-test/.yarn/__virtual__/@pnpm-npm-resolver-virtual-1b644e1381/0/cache/@pnpm-npm-resolver-npm-18.0.0-c814e1b91c-a35fbc34f9.zip/node_modules/@pnpm/npm-resolver/lib/index.js
- /Users/mookeun/Projects/knip-test/.yarn/cache/@pnpm-workspace.pkgs-graph-npm-2.0.11-47d882f261-c2f5448adc.zip/node_modules/@pnpm/workspace.pkgs-graph/lib/index.js
    at require$$0.Module._resolveFilename (/Users/mookeun/Projects/knip-test/.pnp.cjs:10938:13)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at require$$0.Module._load (/Users/mookeun/Projects/knip-test/.pnp.cjs:10827:31)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (/Users/mookeun/Projects/knip-test/.yarn/__virtual__/@pnpm-npm-resolver-virtual-1b644e1381/0/cache/@pnpm-npm-resolver-npm-18.0.0-c814e1b91c-a35fbc34f9.zip/node_modules/@pnpm/npm-resolver/lib/pickPackage.js:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at require$$0.Module._extensions..js (/Users/mookeun/Projects/knip-test/.pnp.cjs:10982:33)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
```

**Comment by webpro** [comment] 2023-11-28 06:24
Looks like a duplicate of #327 - not an issue with Knip.

**Closed** 2023-12-01 13:23 UTC
Labels: bug
