### ISSUE TITLE
Detect imports across workspace packages in a monorepo

### ISSUE THREAD

**Issue by tasercake** [webpro/knip#259] opened 2023-09-22 06:13 UTC
I have a monorepo with 2 packages `foo` and `bar`.
`bar/index.js` imports from `foo/lib.js`, but knip flags `foo/lib.js` as unused.

Repro: https://github.com/tasercake/knip-workspace-bug

```console
$ yarn
$ yarn knip
 yarn run v1.22.19
 $ /Users/krishna/Documents/hypotenuse/knip-workspace-bug/node_modules/.bin/knip
 Unused files (1)
 foo/lib.js
 error Command failed with exit code 1.
 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I would expect `foo/lib.js` to _not_ be flagged as unused because it's imported & used in `bar/index.js`

Looked around at previous issues but I'm not sure any of them cover my exact problem. https://github.com/webpro/knip/issues/140#issuecomment-1570649718 seems to suggest that knip should be aware of imports across packages.

I'm using yarn v1.22.19 (classic) and set up the monorepo according to the classic instructions. To check if that might be the root cause I tried porting the repo over to modern yarn (v3.6.3): https://github.com/tasercake/knip-workspace-bug/tree/yarn-modern, but I get the same output from knip

**Comment by webpro** [comment] 2023-09-23 06:50
Sounds like a duplicate of #244, let's track it over there :)

**Closed by webpro** 2023-09-23 06:50 UTC
Labels: discussion
