### ISSUE TITLE
"Unused item in ..." after upgrading to v2.9.0

### ISSUE THREAD

**Issue by XDoubleU** [webpro/knip#120] opened 2023-04-16 15:16 UTC
On v2.3.1 my knip configuration had no issues. However, after upgrading to v2.9.0 I get following output:
```
Unused dependencies (1)
@mikro-orm/cli  packages/mikro-orm-config/package.json
Unlisted dependencies (1)
mikro-orm  packages/mikro-orm-config/package.json
Configuration issues (5)
Unused item in ignoreBinaries: eslint
Unused item in ignoreBinaries: tsc
Unused item in ignoreBinaries (workspace: apps/web): eslint
Unused item in ignoreBinaries (workspace: packages/mikro-orm-config): eslint
Unused item in ignoreWorkspaces: packages/eslint-config-custom
```

I have attached a zip containing the folder structure of my project with only my `knip.json` and every `package.json` inside. If any other information could help, please let me know.
[check-in.zip](https://github.com/webpro/knip/files/11242605/check-in.zip)

**Comment by webpro** [comment] 2023-04-17 21:20
Thanks for the report and the attached files. That's useful.

```
Unused dependencies (1)
@mikro-orm/cli  packages/mikro-orm-config/package.json
Unlisted dependencies (1)
mikro-orm  packages/mikro-orm-config/package.json
```

I think the `npx mikro-orm` is the culprit here. It means that the `@mikro-orm/cli` is not used, but instead `npx` is going to use the `mikro-orm` package. I think you should omit `npx` here and execute the `mikro-orm` binary directly (from the `@mikro-orm/cli` package).

In other words: removing `npx` should fix the issue. There have been some improvements in Knip around binaries and now Knip reveals this issue in `packages/mikro-orm-config/package.json`.

```
Unused item in ignoreBinaries: eslint
Unused item in ignoreBinaries: tsc
Unused item in ignoreBinaries (workspace: apps/web): eslint
Unused item in ignoreBinaries (workspace: packages/mikro-orm-config): eslint
Unused item in ignoreWorkspaces: packages/eslint-config-custom
```

Will look into this part tomorrow (not breaking).

**Comment by webpro** [comment] 2023-04-20 09:47
:rocket: _This issue has been resolved in v2.10.0. See [Release 2.10.0](https://github.com/webpro/knip/releases/tag/2.10.0) for release notes._

**Closed by webpro** 2023-04-20 09:47 UTC
Labels: bug

**Comment by webpro** [comment] 2023-04-20 09:49
Things should look better now. Likely `tsc` will appear as unused item in ignoreBinaries, since `typescript` is a globally ignored dependency.

Thanks again for reporting this!

**Comment by XDoubleU** [comment] 2023-04-20 16:02
Thanks for looking into it. After updating the results did get worse:
```
Unused files (1)
packages/eslint-config-custom/nextjs.js
Unused devDependencies (11)
@typescript-eslint/eslint-plugin   packages/eslint-config-custom/package.json
@typescript-eslint/parser          packages/eslint-config-custom/package.json
eslint-config-next                 packages/eslint-config-custom/package.json
eslint-config-prettier             packages/eslint-config-custom/package.json
eslint-config-turbo                packages/eslint-config-custom/package.json
eslint-plugin-import               packages/eslint-config-custom/package.json
eslint-plugin-prettier             packages/eslint-config-custom/package.json
eslint-plugin-redundant-undefined  packages/eslint-config-custom/package.json
eslint-plugin-sonarjs              packages/eslint-config-custom/package.json
eslint-plugin-turbo                packages/eslint-config-custom/package.json
prettier                           packages/eslint-config-custom/package.json
Unused exports (1)
default  packages/eslint-config-custom/shared.js
Configuration issues (2)
Unused item in ignoreDependencies: tsconfig-custom
Unused item in ignoreDependencies: eslint-config-custom
error Command failed with exit code 13.
```

I am still using the same `knip.json`.  The biggest issue here seems to be the workspace that's not ignored anymore, which might have been caused by [this change](https://github.com/webpro/knip/commit/0ad317c41fcb74db20814884f188d3c20f3341fa#diff-2b77c49353c0a694655101966253bccf1e23d6f9b1f2dde0056dbb6700b883fdL240)

**Comment by webpro** [comment] 2023-04-22 11:41
Oops! Got distracted by fixing #97 based on your test case :)

Added a test to prevent regressions. Thanks again for reporting.

**Comment by XDoubleU** [comment] 2023-04-22 11:43
No problem, thanks for responding so quick all the time! You're a great maintainer! Enjoy your weekend!

**Comment by webpro** [comment] 2023-04-22 12:05
Thanks Xander, have a great one too 🙏
