### ISSUE TITLE
TS: Exported variable 'X' has or is using name 'Y' from external module "Z" but cannot be named

### ISSUE THREAD

**Issue by gajus** [webpro/knip#324] opened 2023-10-30 17:50 UTC
https://stackoverflow.com/a/77390832/368691

The StackOverflow answer has all the context, but the main problem here is that Knip recommended something to be removed because it is not being consumed, but that broke applications that depend on this package.

I am not familiar with why TypeScript would need this type to be exported though. Might be worth tagging some folks from TypeScript team on this issue.

**Comment by gajus** [comment] 2023-11-02 16:51
This has become a major issue after migrating to `moduleResolution` `NodeNext`.

https://github.com/microsoft/TypeScript/issues/47663

The only thing that so far saves us is setting:

```json
"declaration": false,
"declarationMap": false,
```

at the application level.

**Comment by webpro** [comment] 2023-11-03 13:21
For what it's worth, Knip has uses/sets/overrides to `moduleResolution: ts.ModuleResolutionKind.NodeNext` for said purpose basically since the beginning.

Need to dig into this deeper, but is this not an issue when compiling your code, but it is when running Knip?

**Comment by gajus** [comment] 2023-11-03 13:25
We get this when compiling the code after applying Knip suggestions.

**Comment by webpro** [comment] 2023-11-03 13:31
Right, that sounds like Knip reported some false positives, and maybe the issue is with TypeScript itself. In the linked SO comment I see you reference https://github.com/gajus/roarr/commit/5c4e8d373db96c91ee3b0cd7c543ed72bf158791, so that would be the reproduction I could look into?

**Comment by gajus** [comment] 2023-11-03 13:38
If you try version https://github.com/gajus/roarr/releases/tag/v7.18.0 that should help to repro the issue.

If you cannot, let me know and I will setup a repro.

**Comment by webpro** [comment] 2023-11-03 15:43
Sounds like we all agree that something should not be exported. But not exporting it breaks other packages.

I guess the ask is whether Knip should (not) report it. But at this point, if I understand correctly, I'd rather see a fix on the TS end.

**Comment by gajus** [comment] 2023-11-03 16:18
> I guess the ask is whether Knip should (not) report it. But at this point, if I understand correctly, I'd rather see a fix on the TS end.

I am honestly completely lost about this one. I cannot even figure out how to fix it sometimes because TypeScript errors do not identify which types need to be exported.

So far I found though that it is usually the `interface`s that are causing the problem and sometimes simply changing interface to a `type` fixes the issue. Slonik issue I linked though shows thats not always the case.

**Comment by webpro** [comment] 2023-12-15 07:45
Cleaning up the issue list a bit, so I'm going to close this issue.

Recent versions may have improved the situation a bit, but since we think it's a TypeScript issue, there's probably no solution yet?

You may want to try the [--isolate-workspaces](https://knip.dev/reference/cli/#--isolate-workspaces) option I've introduced recently to enforce isolating the workspaces so they each use their own `tsconfig.json` settings (Knip shares them whenever possible to improve performance and reduce memory usage).

You also may want to try v4 canary, since that version refactors the way imports and exports are matched against each other. I expect in this case it won't help much.

Not sure how to repro the issue, so leaving it at this for now.

**Closed by webpro** 2023-12-15 07:45 UTC
Labels: discussion

**Comment by webpro** [comment] 2024-04-26 10:33
For what it's worth, this may be fixed in TS v5.5:

https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#consulting-packagejson-dependencies-for-declaration-file-generation
