### ISSUE TITLE
Knip doesn't understand npm aliases

### ISSUE THREAD

**Issue by Faithfinder** [webpro/knip#474] opened 2024-01-25 15:28 UTC
I think in this case [repro](https://codesandbox.io/p/devbox/knip-npm-alias-repro-htr24p?file=%2Fpackage.json%3A3%2C22&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrsasof30006356n1g7nu728%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrsasof30002356nsi7dek6r%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrsasof30004356n6vokpb8f%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrsasof30005356ngf11sj0n%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrsasof30002356nsi7dek6r%2522%253A%257B%2522id%2522%253A%2522clrsasof30002356nsi7dek6r%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrtcuzg6002e356mckft4e2v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A3%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A3%252C%2522endColumn%2522%253A22%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrtcuzg6002e356mckft4e2v%2522%257D%252C%2522clrsasof30005356ngf11sj0n%2522%253A%257B%2522id%2522%253A%2522clrsasof30005356ngf11sj0n%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clrsasof30004356n6vokpb8f%2522%253A%257B%2522id%2522%253A%2522clrsasof30004356n6vokpb8f%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrsasof30003356n681x71dt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clrtczm7t00tl356mvtwv9daz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clrtczm1y0008eege9lqmcrfv%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrsasof30003356n681x71dt%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) is self-sufficient

**Comment by webpro** [comment] 2024-01-29 11:56
Can't reproduce this. The import `react-select3` in `src/index.ts` is matched against the `react-select3` dependency name in `package.json`.

Did you `npm install` the `node_modules` first?

**Comment by Faithfinder** [comment] 2024-01-29 14:14
Of course, and also, I believe codesandbox installs deps automatically? (this is a minimal repro from our own rush repository BTW)

![image](https://github.com/webpro/knip/assets/25051063/66c6d6f1-0d72-4d26-bda5-31e260b80bca)

**Comment by webpro** [comment] 2024-01-29 14:16
When I did this locally, there were no false positives. From your screenshot I don't see `node_modules` either (I can imagine CSB hides, I don't know).

**Comment by Faithfinder** [comment] 2024-01-29 14:37
Here's a local copy and screenshot :) CSB indeed hides node_modules, but they're there :)
https://github.com/Faithfinder/knip-npm-alias-repro

![image](https://github.com/webpro/knip/assets/25051063/e9919cca-f20e-43d2-8e3a-c7dc1cc8676c)

**Comment by Faithfinder** [comment] 2024-01-29 14:43
BTW, it's not exactly a false positive/negative. You might notice, there's _two_ errors produced.

Unused dependency `react-select3` and Unlisted dependency `react-select`. With unlisted, I sorta wonder how `knip` resolves identifier `react-select3` in `index.ts` to know that it's `react-select`, but _not_ know that it's listed

**Comment by webpro** [comment] 2024-01-29 19:25
:rocket: _This issue has been resolved in v4.2.2. See [Release 4.2.2](https://github.com/webpro/knip/releases/tag/4.2.2) for release notes._

**Closed by webpro** 2024-01-29 19:25 UTC
Labels: bug

**Comment by webpro** [comment] 2024-01-29 19:26
Sometimes we can just remove code to fix stuff. Thanks for reporting this, @Faithfinder!
