### ISSUE TITLE
Support for React Native platform specific files

### ISSUE THREAD

**Issue by thomasttvo** [webpro/knip#295] opened 2023-10-11 19:23 UTC
Right now exports in `X.android.ts` or `X.ios.ts` files are considered unused. It'd be great if the parser knows that `import X` should include these files.

**Comment by webpro** [comment] 2023-10-11 20:43
Duplicate of #126. Please continue the discussion over there, I can re-open if necessary.

**Closed by webpro** 2023-10-11 20:43 UTC
Labels: feature request
