### ISSUE TITLE
Package.json exports are reported as unused files in a monorepo, even if they are directly used.

### ISSUE THREAD

**Issue by vacavaca** [webpro/knip#412] opened 2023-12-21 18:44 UTC
Here is the reproduction repo: https://github.com/vacavaca/knip-error

Im just using the defaults, no custom config, also nothing suspicious in the output of `knip --debug`

**Comment by webpro** [comment] 2024-01-02 14:21
This looks like intended behavior: `@kniprepro/one/inner` points to `"./inner": "./build/inner/index.js"` so `packages/one/src/inner/index.ts` remains unused.

**Comment by webpro** [comment] 2024-01-02 14:23
The title of this issue seems incorrect, Knip does not report the file configured in `package.json#exports` as unused.

**Comment by vacavaca** [comment] 2024-01-03 21:00
Yeah, that's true. The issue seems to be that src/ and build/ (from the package.json#exports field) are different directories, but to me, it seems like a more or less standard way to structure Node.js projects in TypeScript. Files inside the build/ directory are "linked" with src/ files via source maps, and I thought Knip should use that, or maybe some other information, to better relate build and source files.

I think I could come up with a semi-automatic solution for that on my side, but do you consider looking into that too? Maybe as a feature request. I believe it would be beneficial to make Knip work on a larger set of projects out of the box.

**Comment by webpro** [comment] 2024-01-04 10:22
> I think I could come up with a semi-automatic solution for that on my side

I'd recommend to go the common route of ignoring generated files and adding entry files to the Knip config as necessary.

> but do you consider looking into that too? Maybe as a feature request. I believe it would be beneficial to make Knip work on a larger set of projects out of the box.

I'd love to, but how can Knip reliably link `dist/index.ts` to `src/index.ts`? I mean, without going into very specific build or bundler configuration area? Feels like a rabbit hole tbh, but I'm very much open to ideas here.

Closing this issue as "works as intended", but feel free to discuss further.

**Closed by webpro** 2024-01-04 10:22 UTC
Labels: bug

**Comment by vacavaca** [comment] 2024-01-09 19:40
> I'd love to, but how can Knip reliably link dist/index.ts to src/index.ts?

How about source-map files? They provide the info about this link in an easy-to-use way. They are also usually enabled in the tsconfig in development to enable the 'go to definition' functionality in code editors.

> I'd recommend to go the common route of ignoring generated files and adding entry files to the Knip config as necessary.

Yeah, I built the script inside `knip.js` to automatically populate the config based on the package.json, replacing paths in the `exports` field from "build/\*.js" to "src/\*.ts".
